repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9 # Ruff version
    hooks:
      - id: ruff # Linting
      - id: ruff-format # Formatting

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2 # nbstripout version
    hooks:
      - id: nbstripout
        args: ['--extra-keys=metadata.celltoolbar cell.metadata.heading_collapsed']